/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MarvelPunks, MarvelPunksCollection } from '.';

let contracts = undefined;
export function getContractByCodeHash(codeHash) {
  if (contracts === undefined) {
    contracts = [MarvelPunks, MarvelPunksCollection];
  }
  const c = contracts.find(c => c.contract.hasCodeHash(codeHash));
  if (c === undefined) {
    throw new Error('Unknown code with code hash: ' + codeHash);
  }
  return c.contract;
}
