/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as MarvelPunksContractJson } from "../MarvelPunks.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace MarvelPunksTypes {
  export type Fields = {
    collectionId: HexString;
    nftIndex: bigint;
    uri: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getTokenUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getCollectionIndex: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[HexString, bigint]>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getTokenUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getCollectionIndex: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  MarvelPunksInstance,
  MarvelPunksTypes.Fields
> {
  encodeFields(fields: MarvelPunksTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  at(address: string): MarvelPunksInstance {
    return new MarvelPunksInstance(address);
  }

  tests = {
    getTokenUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<MarvelPunksTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getTokenUri", params, getContractByCodeHash);
    },
    getCollectionIndex: async (
      params: Omit<
        TestContractParamsWithoutMaps<MarvelPunksTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<[HexString, bigint]>> => {
      return testMethod(
        this,
        "getCollectionIndex",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: MarvelPunksTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const MarvelPunks = new Factory(
  Contract.fromJson(
    MarvelPunksContractJson,
    "",
    "4897086210869e612d82995b765a447c5319a55a56e8a0c3c07b4d9ca81e15b1",
    []
  )
);

// Use this class to interact with the blockchain
export class MarvelPunksInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<MarvelPunksTypes.State> {
    return fetchContractState(MarvelPunks, this);
  }

  view = {
    getTokenUri: async (
      params?: MarvelPunksTypes.CallMethodParams<"getTokenUri">
    ): Promise<MarvelPunksTypes.CallMethodResult<"getTokenUri">> => {
      return callMethod(
        MarvelPunks,
        this,
        "getTokenUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCollectionIndex: async (
      params?: MarvelPunksTypes.CallMethodParams<"getCollectionIndex">
    ): Promise<MarvelPunksTypes.CallMethodResult<"getCollectionIndex">> => {
      return callMethod(
        MarvelPunks,
        this,
        "getCollectionIndex",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getTokenUri: async (
      params: MarvelPunksTypes.SignExecuteMethodParams<"getTokenUri">
    ): Promise<MarvelPunksTypes.SignExecuteMethodResult<"getTokenUri">> => {
      return signExecuteMethod(MarvelPunks, this, "getTokenUri", params);
    },
    getCollectionIndex: async (
      params: MarvelPunksTypes.SignExecuteMethodParams<"getCollectionIndex">
    ): Promise<
      MarvelPunksTypes.SignExecuteMethodResult<"getCollectionIndex">
    > => {
      return signExecuteMethod(MarvelPunks, this, "getCollectionIndex", params);
    },
  };

  async multicall<Callss extends MarvelPunksTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<MarvelPunksTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      MarvelPunks,
      this,
      callss,
      getContractByCodeHash
    )) as MarvelPunksTypes.MulticallReturnType<Callss>;
  }
}
