/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as MarvelPunksCollectionContractJson } from "../MarvelPunksCollection.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace MarvelPunksCollectionTypes {
  export type Fields = {
    nftTemplateId: HexString;
    collectionUri: HexString;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; nftIndex: bigint }>;
      result: CallContractResult<null>;
    };
    mint: {
      params: CallContractParams<{ nftUri: HexString }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        nftIndex: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: SignExecuteContractMethodParams<{ nftUri: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  MarvelPunksCollectionInstance,
  MarvelPunksCollectionTypes.Fields
> {
  encodeFields(fields: MarvelPunksCollectionTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  consts = {
    ErrorCodes: {
      IncorrectTokenIndex: BigInt("0"),
      NFTNotFound: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
    },
  };

  at(address: string): MarvelPunksCollectionInstance {
    return new MarvelPunksCollectionInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<MarvelPunksCollectionTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<MarvelPunksCollectionTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        MarvelPunksCollectionTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        MarvelPunksCollectionTypes.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    mint: async (
      params: TestContractParamsWithoutMaps<
        MarvelPunksCollectionTypes.Fields,
        { nftUri: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: MarvelPunksCollectionTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const MarvelPunksCollection = new Factory(
  Contract.fromJson(
    MarvelPunksCollectionContractJson,
    "",
    "087f9292bb326a4d39a6fac09928cb25edf2837718f830f3a166a937f8724779",
    []
  )
);

// Use this class to interact with the blockchain
export class MarvelPunksCollectionInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<MarvelPunksCollectionTypes.State> {
    return fetchContractState(MarvelPunksCollection, this);
  }

  view = {
    getCollectionUri: async (
      params?: MarvelPunksCollectionTypes.CallMethodParams<"getCollectionUri">
    ): Promise<
      MarvelPunksCollectionTypes.CallMethodResult<"getCollectionUri">
    > => {
      return callMethod(
        MarvelPunksCollection,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: MarvelPunksCollectionTypes.CallMethodParams<"totalSupply">
    ): Promise<MarvelPunksCollectionTypes.CallMethodResult<"totalSupply">> => {
      return callMethod(
        MarvelPunksCollection,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: MarvelPunksCollectionTypes.CallMethodParams<"nftByIndex">
    ): Promise<MarvelPunksCollectionTypes.CallMethodResult<"nftByIndex">> => {
      return callMethod(
        MarvelPunksCollection,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: MarvelPunksCollectionTypes.CallMethodParams<"validateNFT">
    ): Promise<MarvelPunksCollectionTypes.CallMethodResult<"validateNFT">> => {
      return callMethod(
        MarvelPunksCollection,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: MarvelPunksCollectionTypes.CallMethodParams<"mint">
    ): Promise<MarvelPunksCollectionTypes.CallMethodResult<"mint">> => {
      return callMethod(
        MarvelPunksCollection,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: MarvelPunksCollectionTypes.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<
      MarvelPunksCollectionTypes.SignExecuteMethodResult<"getCollectionUri">
    > => {
      return signExecuteMethod(
        MarvelPunksCollection,
        this,
        "getCollectionUri",
        params
      );
    },
    totalSupply: async (
      params: MarvelPunksCollectionTypes.SignExecuteMethodParams<"totalSupply">
    ): Promise<
      MarvelPunksCollectionTypes.SignExecuteMethodResult<"totalSupply">
    > => {
      return signExecuteMethod(
        MarvelPunksCollection,
        this,
        "totalSupply",
        params
      );
    },
    nftByIndex: async (
      params: MarvelPunksCollectionTypes.SignExecuteMethodParams<"nftByIndex">
    ): Promise<
      MarvelPunksCollectionTypes.SignExecuteMethodResult<"nftByIndex">
    > => {
      return signExecuteMethod(
        MarvelPunksCollection,
        this,
        "nftByIndex",
        params
      );
    },
    validateNFT: async (
      params: MarvelPunksCollectionTypes.SignExecuteMethodParams<"validateNFT">
    ): Promise<
      MarvelPunksCollectionTypes.SignExecuteMethodResult<"validateNFT">
    > => {
      return signExecuteMethod(
        MarvelPunksCollection,
        this,
        "validateNFT",
        params
      );
    },
    mint: async (
      params: MarvelPunksCollectionTypes.SignExecuteMethodParams<"mint">
    ): Promise<MarvelPunksCollectionTypes.SignExecuteMethodResult<"mint">> => {
      return signExecuteMethod(MarvelPunksCollection, this, "mint", params);
    },
  };

  async multicall<Callss extends MarvelPunksCollectionTypes.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<MarvelPunksCollectionTypes.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      MarvelPunksCollection,
      this,
      callss,
      getContractByCodeHash
    )) as MarvelPunksCollectionTypes.MulticallReturnType<Callss>;
  }
}
