/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ExecutableScript, Script } from '@alephium/web3';
import { default as MintScriptJson } from '../Mint.ral.json';
import { getContractByCodeHash } from './contracts';

export const Mint = new ExecutableScript(
  Script.fromJson(MintScriptJson, '', []),
  getContractByCodeHash,
);
